version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      # Install latest versions of browsers and their corresponding drivers
      - run:
          name: Install Browsers and WebDriverManager
          command: |
            sudo apt-get update && sudo apt-get install -y wget firefox
            # Install Google Chrome
            wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
            # Install ChromeDriver (ensure version compatibility with Chrome)
            wget -q https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            # Install GeckoDriver for Firefox
            wget -q https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
            tar -xzf geckodriver-v0.30.0-linux64.tar.gz
            sudo mv geckodriver /usr/local/bin/

      - run:
          name: Clean and Build
          command: mvn clean install -DskipTests

      - run:
          name: Test
          command: mvn test

      - store_test_results:
          path: target/surefire-reports/junitreports

      - store_artifacts:
          path: test-report
          destination: test-report

workflows:
  sample:
    jobs:
      - build-and-test